name: Linearizability
on: [push, pull_request]
permissions: read-all
jobs:
  test:
    uses: ./.github/workflows/linearizability-template.yaml
    with:
      ref: ${{ github.ref }}
      count: 30
      testTimeout: 30m
